default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: qwertyui
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: ajax_rails_development

test:
  <<: *default
  database: ajax_rails_test
production:
  <<: *default
  database: ajax_rails_production
  username: ajax_rails
  password: <%= ENV['AJAX_RAILS_DATABASE_PASSWORD'] %>
